language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

  - DB=mysql

matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  allow_failures:
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: hhvm


before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit